# Fetching all runs to get total mileage
query GetAllRuns @auth(level: PUBLIC) {
  runs(orderBy: [{date: DESC}]) {
    id
    date
    distanceMiles
    durationMinutes
  }
}

# Fetching all restaurants for display 
query GetAllRestaurants @auth(level: PUBLIC) {
  restaurants {
    id
    name
    cuisine
    milesRequired
    isVisited
  }
}

query GetAllRunsAndRestaurants @auth( level: PUBLIC){
  runs {
    id
    date
    distanceMiles
    durationMinutes
  }
  restaurants {
    id
    name
    cuisine
    milesRequired
    isVisited
  }
}

query GetMileage @auth( level: PUBLIC){
  mileages {
    id
    netMiles
  }
}

##MUTATIONS

#Creating a new run entry
mutation AddRun($date: Date!, $distanceMiles: Float!, $durationMinutes: Int!) @auth( level: PUBLIC) {
  run_insert(data:{
    date: $date
    distanceMiles: $distanceMiles 
    durationMinutes: $durationMinutes
})
}
#creating a new restaurant entry
mutation AddRestaurant($name: String!, $cuisine: String!, $milesRequired: Float!) @auth( level: PUBLIC){
  restaurant_insert(data:{
    name: $name
    cuisine: $cuisine
    milesRequired: $milesRequired 
    ##isVisited will default to false
})
}
# Marking a restaurant as visited
mutation MarkRestaurantVisited($id: UUID!) @auth( level: PUBLIC){
  restaurant_update(id: $id, data:{
    isVisited: true
})
}
# Marking a restaurant as not visited
mutation UnmarkRestaurantVisited($id: UUID!) @auth( level: PUBLIC){
  restaurant_update(id: $id, data: {
    isVisited: false
  })
}

mutation deleteRestaurant($id: UUID!) @auth( level: PUBLIC){
  restaurant_delete(id: $id)
}

## Updating mileage after a run is added
mutation UpdateMileageAfterRun($id: UUID!, $netMiles: Float!) @auth( level: PUBLIC){
  mileage_update(id: $id, data: {
    netMiles: $netMiles
  })
} 

## Setting a mileage (at the start up execution):

mutation CreateMileage($netMiles: Float!) @auth( level: PUBLIC){
  mileage_insert(data: { netMiles: $netMiles })
}