# Fetching all runs to get total mileage
query GetAllRuns($userId: String!) @auth(expr: "auth.uid == userId") {
  runs(where: {userId: {eq: $userId}}, orderBy: [{date: DESC}]) {
    id
    date
    distanceMiles
    durationMinutes
  }
}

# Fetching all restaurants for display 
query GetAllRestaurants @auth(level: USER) {
  restaurants(orderBy: [{milesRequired: DESC}]) {
    id
    name
    cuisine
    milesRequired
  }
}

query GetAllRunsAndRestaurants($userId: String!) @auth(expr: "auth.uid == userId") {
  runs(where: {userId: {eq: $userId}}, orderBy: [{date: DESC}]) {
    id
    date
    distanceMiles
    durationMinutes
  }
  restaurants(orderBy: [{milesRequired: DESC}]) {
    id
    name
    cuisine
    milesRequired
  }
}
query GetVisitedRestaurants($userId: String!) @auth(expr: "auth.uid == userId") {
  visitedRestaurants(where: {userId: {eq: $userId}}, orderBy: [{visitedAt: DESC}]) {
    id
    name
    cuisine
    visitedAt
  }
}

query GetMileage($userId: String!) @auth(expr: "auth.uid == userId") {
  mileage(key: {userId: $userId}) {
    netMiles
  }
}
##MUTATIONS

#Creating a new run entry
mutation AddRun($date: Date!, $distanceMiles: Float!, $durationMinutes: Int!) @auth( level: USER) {
  run_insert(data: {
    userId_expr: "auth.uid"
    date: $date
    distanceMiles: $distanceMiles 
    durationMinutes: $durationMinutes
})
}
#creating a new restaurant entry
mutation AddRestaurant($name: String!, $cuisine: String!, $milesRequired: Float!) @auth( level: NO_ACCESS){
  restaurant_insert(data:{
    name: $name
    cuisine: $cuisine
    milesRequired: $milesRequired 
    ##isVisited will default to false
})
}

#Adding a visited restaurant entry (when a user marks a restaurant as visited)
mutation AddVisitedRestaurant($name: String!, $cuisine: String!) @auth( level: USER){
  visitedRestaurant_insert(data:{
    userId_expr: "auth.uid"
    name: $name
    cuisine: $cuisine
    ##visitedAt will default to current timestamp
})
}

mutation deleteRestaurant($id: UUID!) @auth( level: NO_ACCESS){
  restaurant_delete(id: $id)
}

## Updating mileage after a run is added
mutation UpdateMileageAfterRun($userId: String!, $netMiles: Float!) @auth(expr: "auth.uid == userId") {
  mileage_update(key: {userId: $userId}, data: {
    netMiles: $netMiles
  })
} 

## Setting a mileage (at the start up execution):
mutation CreateMileage($netMiles: Float!) @auth( level: USER){
  mileage_insert(data: { 
    userId_expr: "auth.uid"
    netMiles: $netMiles 
    })
}

# Delete all data from all tables
mutation DeleteAllData @auth(level: USER) {
  run_deleteMany(all: true)
  restaurant_deleteMany(all: true)
  mileage_deleteMany(all: true)
  visitedRestaurant_deleteMany(all: true)
}